---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.example.com
  resources:
  - devclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.example.com
  resources:
  - devclusters/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.example.com
  resources:
  - devclusters/status
  verbs:
  - get
  - patch
  - update
